- name: Setup password file
  become: true
  ansible.builtin.template:
    src: mosquitto.passwd.j2
    dest: "{{ alemuro_mosquitto_password_file }}"
    owner: mosquitto
    group: mosquitto
    mode: "0640"
  when: alemuro_mosquitto_password_file is not none
  notify:
    - Restart mosquitto

- name: Setup local config
  become: true
  ansible.builtin.template:
    src: mosquitto.local.conf.j2
    dest: /etc/mosquitto/conf.d/mosquitto.local.conf
    mode: "0644"
  notify:
    - Restart mosquitto
