---
# tasks file for alemuro.mosquitto

- name: Install Mosquitto
  ansible.builtin.include_tasks: install.yml
  tags:
    - build

- name: Install Mosquitto
  ansible.builtin.include_tasks: configure.yml
  tags:
    - configure
